### ISSUE TITLE
FAQ - Add Why should I use conda? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#46] opened 2023-02-06 20:54 UTC
## Description

Add the question "Why should I use conda?" to the conda.org FAQ (docs/faq.md) and answer it. This answer should go over the problems that conda solves.

**Comment by kathatherine** [comment] 2023-02-09 18:59
The answer to this question could also go into more newbie questions like, "What is a package for?" and "Why do I need environment management?"

**Comment by travishathaway** [comment] 2023-02-10 13:51
@kathatherine, perhaps, "Why should I use conda?" would be a better question. No one really "needs" conda because there's plenty of other alternatives out there.

**Comment by Shreyas-SAS** [comment] 2023-04-13 14:19
Hi! Can I work on this? I am targeting Conda as a repository to contribute to this year under GSoD. I have been using conda since a year now for various Applications, so I believe that I can contribute to this well. Through this, you can also get an idea of my writing style. So can I start contributing @travishathaway @kathatherine ?

**Comment by Shreyas-SAS** [comment] 2023-04-13 14:25
> You are welcome to submit a PR, @Shreyas-SAS.

Thanks. I will submit a PR soon.

**Comment by Shreyas-SAS** [comment] 2023-04-13 15:00
@kathatherine ma'am, can you please review the PR with id #94 , Please instruct me if you have any suggestions or amendments. Thanks.

**Comment by sitamgithub-MSIT** [comment] 2023-04-26 21:01
@travishathaway @kathatherine If the issue is not resolved then I want to contribute! Can it be assigned to me?

**Comment by Shreyas-SAS** [comment] 2023-05-02 17:42
Hey, @sitamgithub-MSIT, I am really sorry to reply this late. I will be working on the issue. I am waiting for a response from the team, but maybe it will take a bit more time due to the ongoing GSoD selection process.

**Closed** 2023-06-08 19:50 UTC
Labels: content
