### ISSUE TITLE
Full Logo is incorrect

### ISSUE THREAD

**Issue by kenodegard** [conda-incubator/conda-dot-org#108] opened 2023-04-25 16:25 UTC
## Description

The full logo example on the style guide page has a filled C as opposed to the C outlined:

<img width="712" alt="Screenshot 2023-04-25 at 11 24 34 AM" src="https://user-images.githubusercontent.com/4546435/234341357-a3effbcf-e0a8-4dc8-8650-b2fda8de15ed.png">

<img width="379" alt="Screenshot 2023-04-24 at 3 32 19 PM" src="https://user-images.githubusercontent.com/4546435/234110107-8945e70b-304d-4104-8b30-ffe5a17c3673.png">

Versus the header logo:

<img width="425" alt="Screenshot 2023-04-24 at 3 32 25 PM" src="https://user-images.githubusercontent.com/4546435/234110125-cf70e15a-6941-427f-a795-ad62d1884897.png">

Are we not using the same full conda logo file in both places?

## Tasks

- [ ] Update logo to use C outline instead of filled C

**Comment by travishathaway** [comment] 2023-04-28 08:24
@kenodegard,

So, I trying debugging this recently. We are using the same SVG file in the both places 😤. I think it must be some random CSS rule somewhere affecting this 🤷‍♂️.

I added the https://github.com/conda-incubator/conda-dot-org/labels/good%20first%20issue tag. If you would like to work on this, please say so in the comments. The first person to comment will be assigned the issue.

**Comment by Shreyas-SAS** [comment] 2023-04-28 08:47
Hey! Can I work on this issue? I will start after the 1st of May due to academic commitments if that is OK.

**Comment by travishathaway** [comment] 2023-04-28 08:49
@Shreyas-SAS,

Thanks for volunteering! That is totally okay with us. Good luck on your exams.

**Comment by Shreyas-SAS** [comment] 2023-04-28 11:46
> Thanks for volunteering! That is totally okay with us. Good luck on your exams.

Thanks. I will try to solve the issue asap after finishing my exams.

**Comment by Shreyas-SAS** [comment] 2023-05-02 17:40
Hey @travishathaway, sorry to ask this, but I am a bit confused here. Should 
![image](https://user-images.githubusercontent.com/96542494/235742181-265f9834-29d1-4edd-9d3b-315715dc7db8.png)
I update all logos to the above one or to
![image](https://user-images.githubusercontent.com/96542494/235742785-bf501956-449d-4dc1-8aa1-0cf00d89e64d.png)
this one?

**Comment by Avik-creator** [comment] 2023-05-03 18:06
Want to Work on This Issue? Can I look into this issue.

**Comment by Shreyas-SAS** [comment] 2023-05-03 22:22
> Want to Work on This Issue? Can I look into this issue.

Hey @Avik-creator, I am still actively working on this issue and wanted @travishathaway to check once to ensure I didn't misunderstand the assignment. I would suggest to regularly check for the good-first-issue tag in the issues lists to get a contribution assigned.

**Comment by Shreyas-SAS** [comment] 2023-05-03 22:22
most probably he would be busy with the GSoD selection work.

**Comment by Avik-creator** [comment] 2023-05-04 03:12
Yeah no worries mate @Shreyas-SAS.

**Comment by Shreyas-SAS** [comment] 2023-05-12 18:52
Hey @Avik-creator are you still interested in this. I tried to fix the issue but even I am not able to find the issue with the svg overwrite. I checked for css files but couldn't find the issue anywhere, maybe you can have a look and find the issue.

**Comment by Shreyas-SAS** [comment] 2023-05-12 19:26
@travishathaway I will unassign myself from the issue as I could not find the problem yet. I wish to keep it open for the first one to pull the PR if that is okay with you.

**Comment by Avik-creator** [comment] 2023-05-13 01:58
Please let me see it and if possible by me I will fix it

**Comment by travishathaway** [comment] 2023-05-15 09:59
Hi @Avik-creator,

Thanks for taking a look! No worries @Shreyas-SAS 😅 . I also wasn't able to figure out what was going on 🤷‍♂️.

Good luck @Avik-creator 🤞 .

**Comment by Avik-creator** [comment] 2023-05-15 18:24
@travishathaway Please check it whenever you have time.

**Comment by Shreyas-SAS** [comment] 2023-05-17 20:25
Oh, Great Observations there @Avik-creator. Really Insightful. 
@travishathaway if the issue is solved let's close it to avoid redundant ones.

**Comment by Avik-creator** [comment] 2023-05-17 20:49
No worries. Just making sure that I am contributing to a big open source organisation that is making development easier for us. @travishathaway @Shreyas-SAS

**Closed** 2023-05-23 08:38 UTC
Labels: good first issue
